In [24]:
import numpy as np  

check = np.random.rand(16,10)

print(check)
print(check.shape)



[[0.63068238 0.10528633 0.50724691 0.90402593 0.23177352 0.1060827
  0.81757145 0.43041111 0.50747363 0.52456967]
 [0.94134081 0.61856151 0.7249676  0.74041837 0.82622575 0.96030831
  0.65877593 0.0141585  0.13764135 0.43842228]
 [0.65935382 0.53188772 0.43009701 0.02639425 0.19559776 0.45791244
  0.46213123 0.13341594 0.35455842 0.74782746]
 [0.96123109 0.39596772 0.55444482 0.43754746 0.50803822 0.36626983
  0.21353502 0.63663723 0.88239724 0.91720666]
 [0.78150668 0.46390011 0.40441424 0.69104336 0.65203648 0.83428362
  0.30976678 0.34551758 0.23010951 0.10000867]
 [0.34320151 0.33995115 0.5779391  0.07902931 0.79917113 0.57612412
  0.37395045 0.49839783 0.77891936 0.96342968]
 [0.94374485 0.44748521 0.40947966 0.45404745 0.49739247 0.97781903
  0.77129017 0.75507653 0.46459603 0.09689964]
 [0.30757596 0.14174732 0.22157345 0.8344797  0.822133   0.37559859
  0.95279651 0.56731553 0.10361898 0.59337725]
 [0.04803424 0.75912885 0.04360835 0.99195344 0.96446964 0.27301631
  0.79073681 

In [3]:
import numpy as np
w = np.array([0.5,-0.4])
x=np.array([2,3])

z= x.dot(w) + 0.1
print(z)

-0.10000000000000017


In [8]:
print(np.zeros((1,10)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [1]:
import numpy as np 

j = np.random.rand(3,5)
print(j)

[[0.19802379 0.33129948 0.12467686 0.8034151  0.08183619]
 [0.01089595 0.6740638  0.62830832 0.16732991 0.64114837]
 [0.97000561 0.70806097 0.09031581 0.67065197 0.81763015]]


In [5]:
import numpy as np

class SimpleNN:
    def __init__(self, input_dim, num_neurons,activation='tanh',weight_style=None):
        # Xavier initialization for tanh
        self.activation = activation
        if activation == 'tanh':
            if weight_style == 'std':
              self.w1 = np.random.randn(input_dim, num_neurons) * np.sqrt(1./input_dim)
              self.w2 = np.random.randn(num_neurons, 1) * np.sqrt(1./num_neurons)
            elif weight_style == 'range':
              self.w1 = np.random.rand(input_dim, num_neurons)
              self.w2 = np.random.rand(num_neurons, 1)
        elif activation == 'relu':
            if weight_style == 'range':
                self.w1 = np.random.rand(input_dim, num_neurons)
                self.w2 = np.random.rand(num_neurons, 1)
            elif weight_style == 'std': 
                self.w1 = np.random.randn(input_dim, num_neurons) * np.sqrt(2./input_dim)
                self.w2 = np.random.randn(num_neurons, 1) * np.sqrt(2./num_neurons)

            

            
        self.b1 = np.zeros((1, num_neurons))
        self.b2 = np.zeros((1, 1))
        self.Loss = []

    # ---- Activation ----
    def Tanh(self, x):
        return np.tanh(x)

    def tanh_grad(self, h):
        return 1 - h**2   # derivative w.r.t tanh output
    
    def Relu(self,x):
        return np.maximum(0,x)
    
    def relu_grad(self,x):
         return (x > 0).astype(float)

    # ---- Loss ----
    def error(self, actual, esti):
        return 0.5 * (actual - esti) ** 2

        # ---- Forward ----
    def forward(self, X):
        self.input = X
        self.z1 = self.input.dot(self.w1) + self.b1   # (batch, num_neurons)

        if self.activation == 'tanh':
            self.h1 = self.Tanh(self.z1)
        else:  # relu
            self.h1 = self.Relu(self.z1)

        self.y_hat = self.h1.dot(self.w2) + self.b2   # (batch, 1)
        return self.y_hat






    def backprop(self, target, lr=1e-3, clip_norm=1.0):
        m = target.shape[0]
        loss_val = np.mean(0.5 * (target - self.y_hat)**2)
        self.Loss.append(loss_val)

        # output layer
        dl_dy = (self.y_hat - target) / m        # (batch,1) normalized by batch
        dW2 = self.h1.T.dot(dl_dy)               # (num_neurons,1)
        db2 = np.sum(dl_dy, axis=0, keepdims=True)  # (1,1)

        # hidden layer
        dh = dl_dy.dot(self.w2.T)                # (batch, num_neurons)
        if self.activation == 'tanh':
            dz1 = dh * self.tanh_grad(self.z1)
        else:
            dz1 = dh * self.relu_grad(self.z1)

        dW1 = self.input.T.dot(dz1)              # (input_dim, num_neurons)
        db1 = np.sum(dz1, axis=0, keepdims=True) # (1, num_neurons)

        # gradient clipping (per-matrix)
        def clip(g):
            norm = np.linalg.norm(g)
            if norm > clip_norm:
                return g * (clip_norm / (norm + 1e-12))
            return g

        dW2 = clip(dW2); dW1 = clip(dW1)
        db2 = clip(db2); db1 = clip(db1)

        # update
        self.w2 -= lr * dW2
        self.b2 -= lr * db2
        self.w1 -= lr * dW1
        self.b1 -= lr * db1




In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()
minmax = MinMaxScaler(feature_range=(0,1))

X = np.linspace(-4, 4, 500).reshape(-1,1)
Y = X ** 2  

#std x normalization
Xs = scaler.fit_transform(X)

#range normalization
Xn = minmax.fit_transform(X)
nn = SimpleNN(input_dim=1, num_neurons=100,  activation='relu',weight_style='range')

# Training
epochs = 5000

batch_size = 32
lr = 1e-3




##########################################################################
for epoch in range(epochs):
    perm = np.random.permutation(len(Xn))
    for i in range(0,len(Xn),batch_size):
        idx = perm[i:i+batch_size]
        x_b, y_b = Xn[idx], Y[idx]
        nn.forward(x_b)
        nn.backprop(y_b,lr= lr,clip_norm=1.0)
    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss = {nn.Loss[-1]}")

#final pred 
y_pred = nn.forward(Xn)




nnsd = SimpleNN(input_dim=1, num_neurons=100,  activation='relu',weight_style='std')

for epi in range(epochs):
    perm = np.random.permutation(len(Xs))
    for i in range(0,len(perm),batch_size):
        idx = perm[i:i+batch_size]
        xb,yb = Xs[idx],Y[idx]
        nnsd.forward(xb)
        nnsd.backprop(yb,lr=lr,clip_norm=1.0)
    if epi % 500 == 0:
            print(f'Epoch {epi} Loss = {nnsd.Loss[-1]}')
    

y_pred2 = nnsd.forward(Xs)

fig, axes = plt.subplots(1, 2, figsize=(12,5))

axes[0].plot(X,Y,label="$original X^2$",color='blue')
axes[0].plot(X,y_pred,label='noramlized wieght plot',color='red', linestyle='--')
axes[0].set_title('Range Normalization perdicatation')
axes[0].legend()
axes[0].grid(True)

axes[1].plot(X,Y,label="$original X^2$",color='blue')
axes[1].plot(X,y_pred2,label='std wieght plot',color='green', linestyle='--')
axes[1].set_title('Standardization perdicatation')
axes[1].legend()
axes[1].grid(True)


plt.tight_layout()
plt.show()






Epoch 0, Loss = 52.48882563349393
Epoch 500, Loss = 3.413030000732165
Epoch 1000, Loss = 0.8551418789492267
Epoch 1500, Loss = 0.19312523229505255
Epoch 2000, Loss = 0.08680869416609527
Epoch 2500, Loss = 0.020137158392853894
Epoch 3000, Loss = 0.031256287170937605
Epoch 3500, Loss = 0.00830674171855563
Epoch 4000, Loss = 0.006580486725171419
Epoch 4500, Loss = 0.02410278571913524
Epoch 0 Loss = 15.22141880925248
Epoch 500 Loss = 0.4609990106484031
Epoch 1000 Loss = 0.20350209603121114
Epoch 1500 Loss = 0.11293133188868605
Epoch 2000 Loss = 0.06326377379142727
Epoch 2500 Loss = 0.03539752660524163
Epoch 3000 Loss = 0.025080611667228518
Epoch 3500 Loss = 0.011192225076336647
Epoch 4000 Loss = 0.008171145852381143
Epoch 4500 Loss = 0.00447726144401272


ValueError: '.' is not a valid value for ls; supported values are '-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'

In [72]:
import pickle

with open('simpleNN.pkl','wb') as f:
    pickle.dump(nn,f)

prediction working great


mini sgd

In [7]:
import numpy as np
import matplotlib.pyplot as plt

class SimpleNN:
    def __init__(self, input_dim, num_neurons, activation='tanh'):
        self.activation = activation
        fan_in, fan_out = input_dim, num_neurons
        # Xavier init (good for tanh); for ReLU use He: * np.sqrt(2/fan_in)
        std1 = np.sqrt(2.0 / (fan_in + fan_out))
        self.w1 = np.random.randn(fan_in, fan_out) * std1
        self.b1 = np.zeros((1, fan_out))
        std2 = np.sqrt(2.0 / (fan_out + 1))
        self.w2 = np.random.randn(fan_out, 1) * std2
        self.b2 = np.zeros((1, 1))
        self.Loss = []

    def forward(self, x):
        self.input = x                       # (batch, input_dim)
        self.z1 = x.dot(self.w1) + self.b1   # (batch, num_neurons)
        if self.activation == 'tanh':
            self.h1 = np.tanh(self.z1)
        else:
            self.h1 = np.maximum(0, self.z1)
        self.y_hat = self.h1.dot(self.w2) + self.b2   # (batch,1)
        return self.y_hat

    def relu_grad(self, z): return (z > 0).astype(float)
    def tanh_grad(self, z): return 1.0 - np.tanh(z)**2

   
    def backprop(self, target, lr=1e-3, clip_norm=1.0):
        m = target.shape[0]
        loss_val = np.mean(0.5 * (target - self.y_hat)**2)
        self.Loss.append(loss_val)

        # output layer
        dL_dy = (self.y_hat - target) / m        # (batch,1) normalized by batch
        dW2 = self.h1.T.dot(dL_dy)               # (num_neurons,1)
        db2 = np.sum(dL_dy, axis=0, keepdims=True)  # (1,1)

        # hidden layer
        dh = dL_dy.dot(self.w2.T)                # (batch, num_neurons)
        if self.activation == 'tanh':
            dz1 = dh * self.tanh_grad(self.z1)
        else:
            dz1 = dh * self.relu_grad(self.z1)

        dW1 = self.input.T.dot(dz1)              # (input_dim, num_neurons)
        db1 = np.sum(dz1, axis=0, keepdims=True) # (1, num_neurons)

        # gradient clipping (per-matrix)
        def clip(g):
            norm = np.linalg.norm(g)
            if norm > clip_norm:
                return g * (clip_norm / (norm + 1e-12))
            return g

        dW2 = clip(dW2); dW1 = clip(dW1)
        db2 = clip(db2); db1 = clip(db1)

        # update
        self.w2 -= lr * dW2
        self.b2 -= lr * db2
        self.w1 -= lr * dW1
        self.b1 -= lr * db1



In [75]:
# ---- data prep ----
X = np.linspace(-4, 4, 500).reshape(-1,1)
Y = X ** 2 


# normalize X (important)
X_mean, X_std = X.mean(axis=0), X.std(axis=0) + 1e-12
Xn = (X - X_mean) / X_std

# model & train
nn = SimpleNN(input_dim=1, num_neurons=50, activation='relu')
epochs = 4000
batch_size = 32
lr = 1e-3

for epoch in range(epochs):
    # mini-batch SGD
    perm = np.random.permutation(len(Xn))
    for i in range(0, len(Xn), batch_size):
        idx = perm[i:i+batch_size]
        xb, yb = Xn[idx], Y[idx]
        nn.forward(xb)
        nn.backprop(yb, lr=lr, clip_norm=1.0)

    if epoch % 400 == 0:
        print(epoch, "loss", nn.Loss[-1])

# final predictions (remember to feed normalized X)
Y_pred = nn.forward(Xn)

# plot
plt.figure(figsize=(8,6))
plt.plot(X, Y, label='True y=x^2')
plt.plot(X, Y_pred, '--', label='NN prediction')
plt.legend()
plt.show()


0 loss 34.07963445015221
400 loss 0.20531829112450484
800 loss 0.12016665908814408
1200 loss 0.016343407995994683
1600 loss 0.013004564430911811
2000 loss 0.008121102367191674
2400 loss 0.010820689309717257
2800 loss 0.011840122459658656
3200 loss 0.0015248982501494762
3600 loss 0.002647348671285177


In [ ]:
np.random.randn(1,10)
np.random.rand(1,1)

array([[0.75400846]])

In [ ]:
w1 = np.random.randn(len(sj[0]),10)
print(w1)

[[-0.19676056  0.16468745 -0.5607339   1.12176614 -1.08756729 -0.47916055
   1.12187741  1.03929713  1.10467392 -0.04857982]
 [-0.91589105  0.52584003 -0.27435371 -0.62021767 -1.77368273  0.34618928
  -0.35598258  0.62848684 -0.1310904  -0.33056148]
 [ 0.6478108   0.48655214 -0.99692909 -1.12759586 -0.87386035  0.78793997
   0.69937008  0.30095813 -0.3899366  -0.5683449 ]
 [ 0.02661809 -3.22721494  1.35157811 -0.10780114 -0.3747107  -0.30480217
  -0.91097819 -0.77647777  0.50947325  0.63668326]
 [ 1.54130342  1.02681295 -0.42085492  0.2597463  -0.48352946 -0.26434552
   0.10216859  2.52103253  0.91765373  0.91292789]
 [-2.45682623 -0.08398991  0.24269358  2.01534651 -0.39756909 -0.55528544
   0.60069982 -0.45067194  0.36016177 -0.78679208]
 [ 0.35582381  0.12658794 -1.33221451  0.48256411  0.23349966  0.0325343
   0.49009408  1.0861085   0.58931538  0.07699001]
 [-0.44469301 -1.52464543 -0.82662016  0.2868618  -1.77664394  1.94319569
  -1.08319859 -0.38526992  0.67461749  2.62153648]
 

In [ ]:
b1 = np.random.rand(1,10)
print(b1)

[[0.37136015 0.47849998 0.69728426 0.35779245 0.62526807 0.67768446
  0.12358334 0.80189743 0.94539182 0.89520929]]


In [ ]:
z = sj.dot(w1) + b1

In [ ]:
print(z)


[[ 0.74961423  1.91403196 -4.10821341  4.16096978 -4.9947882  -1.00750881
   1.46829384  3.83396308  4.47444493  3.1153619 ]]


In [ ]:
x = np.array([2,3,4])
wt = np.array([[0.1,0.2,0.3],[1,2,3],[-1,-2,-3]])
bs = np.array([1,2,3])
print(x)
print(x.dot(wt[0])+1,'\n',wt[0])

zj = x.dot(wt.T) + bs
print(zj)

[2 3 4]
3.0 
 [0.1 0.2 0.3]
[  3.  22. -17.]


In [4]:
import torch

x = torch.tensor(2)
t = torch.tensor(4)


m = torch.tensor(3.0,requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)


y = m * x + b

Loss = 0.5 * (y-t)**2

print(f'predeicted is {y} actual is {t}, and loss is {Loss}')



predeicted is 7.0 actual is 4, and loss is 4.5


In [5]:
Loss.backward()

print('Loss : ',Loss.item())
print(f'dl_dw is {m.grad.item()}')
print(f'dl_dw is {b.grad.item()}')


Loss :  4.5
dl_dw is 6.0
dl_dw is 3.0


In [18]:
x,t = torch.tensor(2), torch.tensor(5)

w1,b1 = torch.tensor(1.0,requires_grad=True), torch.tensor(0.0,requires_grad=True)

w2,b2 = torch.tensor(-1.0,requires_grad=True), torch.tensor(1.0,requires_grad=True)

v1,v2,c = torch.tensor(2.0,requires_grad=True), torch.tensor(-3.0,requires_grad=True), torch.tensor(0.0,requires_grad=True)




In [19]:
h1 = w1*x + b1
h2 = w2*x + b2

print(f'h1 is {h1} and h2 is {h2}')
print(c)

h1 is 2.0 and h2 is -1.0
tensor(0., requires_grad=True)


In [20]:
y = (v1 * h1) + (v2 * h2) + c

print(f'y is: {y}')

loss = 0.5 * (y-t)**2
print(loss)

y is: 7.0
tensor(2., grad_fn=<MulBackward0>)


In [21]:
loss.backward()

print(f'loss grads {loss.item()}')
print(f'w1 and b1 is {w1.grad.item()} and b1 grad is {b1.grad.item()}')
print(f'w2 and b2 is {w2.grad.item()} and b1 grad is {b2.grad.item()}')
print(f'v1 and v2 is {v1.grad.item()} and v2 is {v2.grad.item()} c grad is {c.grad.item()}')


loss grads 2.0
w1 and b1 is 8.0 and b1 grad is 4.0
w2 and b2 is -12.0 and b1 grad is -6.0
v1 and v2 is 4.0 and v2 is -2.0 c grad is 2.0


In [22]:
params = torch.tensor([1.0, 0.0], requires_grad=True)
print(params)

tensor([1., 0.], requires_grad=True)
