In [4]:
import  numpy as np
import pandas as pd
import torch as to

In [5]:
a = to.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [7]:
a[3]

tensor(1.)

In [9]:
import torch
a = torch.zeros(4,5)
b = torch.ones(4,2)
print(a.shape)
print(b.shape)
print(a)
print(b)

torch.Size([4, 5])
torch.Size([4, 2])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [13]:
g = torch.tensor([[3,4,5,6],[3,2,1,3],[35,223,176,33],[35,4352,341,34],[34,245,156,5]])
g

tensor([[   3,    4,    5,    6],
        [   3,    2,    1,    3],
        [  35,  223,  176,   33],
        [  35, 4352,  341,   34],
        [  34,  245,  156,    5]])

In [28]:
k = g[2:3, 1:2]
k
k = 33

k, g[2:3, 1:2]

(33, tensor([[223]]))

In [30]:
print(g)
print(g[0:,0])

tensor([[   3,    4,    5,    6],
        [   3,    2,    1,    3],
        [  35,  223,  176,   33],
        [  35, 4352,  341,   34],
        [  34,  245,  156,    5]])
tensor([ 3,  3, 35, 35, 34])


In [31]:
b = torch.ones(2,3,4,5)
b

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

In [27]:
a = list(range(6))
print(a)
print(a[2:4])
print(a[:-1])

[0, 1, 2, 3, 4, 5]
[2, 3]
[0, 1, 2, 3, 4]


In [33]:
img_t = torch.randn(3, 5, 5)  # [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])  # RGB → grayscale weights
print(img_t)
print(weights)

tensor([[[-0.3549,  0.4488, -0.5713,  1.6525, -2.4589],
         [-0.0893,  1.5963,  0.6509, -1.2570, -0.3850],
         [ 0.0838,  0.0670,  0.6948, -1.2038, -0.8058],
         [ 0.9185,  0.1002,  0.5372,  1.3260, -1.5911],
         [-0.5788, -1.6186, -0.7686,  0.5702, -0.0962]],

        [[-2.3834, -0.9911,  0.4707,  0.2920, -1.5275],
         [-1.0604, -1.1527,  0.0562,  2.3013,  0.4832],
         [ 0.2334, -0.6965, -0.9887, -0.2438, -1.0209],
         [ 1.3014,  0.8189,  1.5436,  0.1854,  0.6965],
         [-0.4147,  0.7635,  1.0151, -2.2906, -0.9164]],

        [[-1.3575,  0.0923, -0.5698,  0.3278,  0.5539],
         [-0.3331,  0.2433, -0.4974, -0.1996, -1.0810],
         [ 0.5464,  0.3327,  0.8216,  0.0715,  0.1902],
         [ 2.2190,  0.0058,  2.2430,  0.7039,  0.0108],
         [ 0.4312, -0.0929, -0.5026, -1.1276, -1.5177]]])
tensor([0.2126, 0.7152, 0.0722])


In [34]:
batch_t = torch.randn(2, 3, 5, 5)  # [batch, channels, rows, columns]
print(batch_t)

tensor([[[[-0.0670, -1.7747, -0.1998,  1.8480,  0.2020],
          [ 1.1906, -0.3898, -1.3563,  1.3240, -0.0549],
          [-0.2086,  1.3215, -0.5451,  0.6962,  0.4347],
          [-2.2377,  1.2473,  0.2707,  0.2116, -0.2011],
          [ 1.4371, -0.4656, -1.6256,  0.9355, -0.8586]],

         [[ 1.4227,  0.9282, -0.2909,  1.0077,  1.2985],
          [-1.9732, -0.1516,  0.9179, -0.2633,  0.8309],
          [-0.6268,  1.3734,  1.3509, -0.7292, -0.5156],
          [-0.8898,  0.5938,  0.9320,  0.6238,  1.2432],
          [ 1.3483, -2.8810,  0.1147, -0.3915, -1.3251]],

         [[-2.1973, -0.4446, -0.6006,  1.4431, -1.0965],
          [-0.5783, -0.1434, -0.2740, -1.1474,  0.6906],
          [-0.2625,  1.2556,  1.0107, -0.4522,  0.9831],
          [-0.0871,  0.8788, -1.0889,  1.0032,  0.7101],
          [-0.5738,  0.5505, -1.2281,  1.3606, -0.7170]]],


        [[[-0.1299,  0.0258,  0.6603, -0.2224, -0.9143],
          [ 0.1064,  0.7587,  2.0715,  0.4130,  1.7153],
          [-0.9546, -0.

In [45]:
print(batch_t.mean(-3))

tensor([[[-0.2805, -0.4304, -0.3638,  1.4329,  0.1346],
         [-0.4537, -0.2282, -0.2375, -0.0289,  0.4889],
         [-0.3660,  1.3168,  0.6055, -0.1617,  0.3007],
         [-1.0716,  0.9066,  0.0380,  0.6129,  0.5841],
         [ 0.7372, -0.9320, -0.9130,  0.6349, -0.9669]],

        [[-0.4853,  0.9054,  0.7421, -0.6077, -0.6688],
         [ 0.1220, -0.1637,  0.1435, -0.1131,  0.6300],
         [ 0.1284,  0.6282, -0.3536, -0.1880, -0.5406],
         [ 0.6355, -0.2970, -0.3978,  0.3931,  0.1904],
         [ 0.7380, -0.0106, -0.1497, -0.7659, -0.8119]]])


In [51]:
x = torch.tensor([10, 20, 30])  # shape (3,)
print(f'shape of x is {x.shape} value of x is {x}\n')

x1 = x.unsqueeze(0)  # add new axis at position 0
print(x1.shape)  # (1, 3)
print(f'value of x1 is {x}')
x2 = x.unsqueeze(1)  # add new axis at position 1
print(x2.shape)  # (3, 1)
print(f'value of x2 is {x2}')
x3 = x2.unsqueeze(2)
print(f'shape of x3 is {x3.shape} value of x is {x3}\n')

x4= x3.unsqueeze(0)
print()
print(f'shape of x4 is {x4.shape} value of x is {x4}\n')


shape of x is torch.Size([3]) value of x is tensor([10, 20, 30])

torch.Size([1, 3])
value of x1 is tensor([10, 20, 30])
torch.Size([3, 1])
value of x2 is tensor([[10],
        [20],
        [30]])
shape of x3 is torch.Size([3, 1, 1]) value of x is tensor([[[10]],

        [[20]],

        [[30]]])


shape of x4 is torch.Size([1, 3, 1, 1]) value of x is tensor([[[[10]],

         [[20]],

         [[30]]]])



In [4]:
import torch
sh = torch.ones(5,4, dtype=torch.double)
print(sh)

print(sh.dtype)

ch = torch.ones(5,4).int()
print(ch)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
torch.float64
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)


In [5]:
vp = torch.randn(5,4).to(torch.float64)
print(vp)

tensor([[ 1.3078, -1.4329, -0.5585,  0.9202],
        [-0.1592, -0.0633,  0.8072,  0.0798],
        [ 0.1067,  0.5823, -0.1084, -1.2932],
        [ 0.2228,  1.2528, -0.4771,  0.1541],
        [ 1.2382, -0.3534,  0.3530, -0.5392]], dtype=torch.float64)


In [6]:
points_64 = torch.rand(5, dtype=torch.double)
print(points_64)

tensor([0.3467, 0.8935, 0.5414, 0.2833, 0.2899], dtype=torch.float64)


In [9]:
arr = torch.arange(5,10,0.1).reshape(-1,5)
print(arr)

tensor([[5.0000, 5.1000, 5.2000, 5.3000, 5.4000],
        [5.5000, 5.6000, 5.7000, 5.8000, 5.9000],
        [6.0000, 6.1000, 6.2000, 6.3000, 6.4000],
        [6.5000, 6.6000, 6.7000, 6.8000, 6.9000],
        [7.0000, 7.1000, 7.2000, 7.3000, 7.4000],
        [7.5000, 7.6000, 7.7000, 7.8000, 7.9000],
        [8.0000, 8.1000, 8.2000, 8.3000, 8.4000],
        [8.5000, 8.6000, 8.7000, 8.8000, 8.9000],
        [9.0000, 9.1000, 9.2000, 9.3000, 9.4000],
        [9.5000, 9.6000, 9.7000, 9.8000, 9.9000]])


In [11]:
a_t = arr.transpose(0,1)
print(a_t)
rch = torch.cat([arr,arr],dim=0)
print(rch)

tensor([[5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000,
         9.5000],
        [5.1000, 5.6000, 6.1000, 6.6000, 7.1000, 7.6000, 8.1000, 8.6000, 9.1000,
         9.6000],
        [5.2000, 5.7000, 6.2000, 6.7000, 7.2000, 7.7000, 8.2000, 8.7000, 9.2000,
         9.7000],
        [5.3000, 5.8000, 6.3000, 6.8000, 7.3000, 7.8000, 8.3000, 8.8000, 9.3000,
         9.8000],
        [5.4000, 5.9000, 6.4000, 6.9000, 7.4000, 7.9000, 8.4000, 8.9000, 9.4000,
         9.9000]])
tensor([[5.0000, 5.1000, 5.2000, 5.3000, 5.4000],
        [5.5000, 5.6000, 5.7000, 5.8000, 5.9000],
        [6.0000, 6.1000, 6.2000, 6.3000, 6.4000],
        [6.5000, 6.6000, 6.7000, 6.8000, 6.9000],
        [7.0000, 7.1000, 7.2000, 7.3000, 7.4000],
        [7.5000, 7.6000, 7.7000, 7.8000, 7.9000],
        [8.0000, 8.1000, 8.2000, 8.3000, 8.4000],
        [8.5000, 8.6000, 8.7000, 8.8000, 8.9000],
        [9.0000, 9.1000, 9.2000, 9.3000, 9.4000],
        [9.5000, 9.6000, 9.7000, 9.8000, 9.9000],
    

In [16]:
x = torch.arange(12).reshape(3, 4)
print(x)
print("shape:", x.shape)
print("stride:", x.stride())


y = x.t()  # transpose
print(y)
print(y.shape)
print(y.stride())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
shape: torch.Size([3, 4])
stride: (4, 1)
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
torch.Size([4, 3])
(1, 4)


In [18]:
f= torch.cross(torch.tensor([2,3,4]), torch.tensor([5,6,7]))  # cross product
g = torch.trace(torch.eye(3))  # trace = sum of diagonal elements → 3
print(f'{f},\n{g}')

tensor([-3,  6, -3]),
3.0


In [25]:
f = torch.rand(4,5)
g= torch.rand(5,7)
c = f + 2
print(c)
h = torch.mm(f,g)
print(h)

torch.save(h, 'tensor2.pt')


tensor([[2.0454, 2.8944, 2.4492, 2.1653, 2.0818],
        [2.7015, 2.9117, 2.4685, 2.3984, 2.0883],
        [2.9548, 2.7539, 2.8108, 2.5858, 2.6286],
        [2.7106, 2.4021, 2.7025, 2.0645, 2.7997]])
tensor([[0.6446, 0.6919, 0.9264, 0.8844, 1.1242, 0.9906, 0.9061],
        [1.1077, 1.1600, 1.6070, 1.7872, 1.5211, 1.6442, 1.0852],
        [1.6329, 1.6808, 2.5387, 2.5053, 2.2027, 2.1489, 1.2649],
        [1.3016, 1.0632, 1.9770, 1.6025, 1.5134, 1.2859, 0.9323]])


In [26]:
c = torch.load('tensor2.pt')
print(c)

tensor([[0.6446, 0.6919, 0.9264, 0.8844, 1.1242, 0.9906, 0.9061],
        [1.1077, 1.1600, 1.6070, 1.7872, 1.5211, 1.6442, 1.0852],
        [1.6329, 1.6808, 2.5387, 2.5053, 2.2027, 2.1489, 1.2649],
        [1.3016, 1.0632, 1.9770, 1.6025, 1.5134, 1.2859, 0.9323]])


C:\Users\khesr\AppData\Local\Temp\ipykernel_14292\2061844681.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  c = torch.load('tensor2.pt')


In [28]:
x = torch.tensor([[4, 1, 5],
                  [3, 2, 1],
                  [3, 2, 1]])
print(x.storage())
# e.g.  4.0, 1.0, 5.0, 3.0, 2.0, 1.0


 4
 1
 5
 3
 2
 1
 3
 2
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]


In [29]:
a = torch.tensor([[4, 1, 5],
                  [3, 2, 1],])

print(a)
print(a.storage())
print(a.stride())
print(a.t())
print(a.t().storage())
print(a.t().stride())

tensor([[4, 1, 5],
        [3, 2, 1]])
 4
 1
 5
 3
 2
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
(3, 1)
tensor([[4, 3],
        [1, 2],
        [5, 1]])
 4
 1
 5
 3
 2
 1
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
(1, 3)


In [32]:
i = torch.tensor([[0, 1, 1], [2, 0, 2]])  # indices
v = torch.tensor([3, 4, 5])               # values
sparse = torch.sparse_coo_tensor(i, v, (2, 3))

print(v,'sparse printing\n\n\n', sparse)

tensor([3, 4, 5]) sparse printing


 tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3, 4, 5]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)
